# Generated by Django 5.1.2 on 2024-10-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["model"],
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ["license_number"]},
        ),
    ]
