# Generated by Django 5.1.2 on 2024-10-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_car_options_alter_driver_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
