# Generated by Django 5.1.2 on 2024-10-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_driver_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(default=0, max_length=63, unique=True),
            preserve_default=False,
        ),
    ]
